/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import javax.swing.JOptionPane;

/**
 *
 * @author Marlon Santos
 */
public class Home extends javax.swing.JFrame {
    Fornecedor fo = new Fornecedor();
    Produto pro = new Produto();
    Cliente cli = new Cliente();
    Comprar com = new Comprar();
    Vender ven = new Vender();
    EstoqueAtual est_a = new EstoqueAtual();
    ProdutoSemEstoque pro_s = new ProdutoSemEstoque();
    DataDeSaida ds = new DataDeSaida();
    DataDeEntrada de = new DataDeEntrada();
    QuantidadeBaixa qb = new QuantidadeBaixa();
    PesCliente pc = new PesCliente();
    PesFornecedor pf = new PesFornecedor();
    PesProduto pp = new PesProduto();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public void ocultar(){
        jPanelHome.setVisible(false);
        fo.setVisible(false);
        pro.setVisible(false);
        cli.setVisible(false);
        com.setVisible(false);
        ven.setVisible(false);
        est_a.setVisible(false);
        pro_s.setVisible(false);
        ds.setVisible(false);
        de.setVisible(false);
        qb.setVisible(false);
        pc.setVisible(false);
        pf.setVisible(false);
        pp.setVisible(false);
    }
    
    public static void ok(){
        JOptionPane.showMessageDialog(null, "OK");
    }
    
    public static void erro(){
        JOptionPane.showMessageDialog(null, "erro");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuCadastar = new javax.swing.JMenu();
        jMenuItemCadastrarFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadastrarProduto = new javax.swing.JMenuItem();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemComprar = new javax.swing.JMenuItem();
        jMenuItemVender = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemEstoqueAtual = new javax.swing.JMenuItem();
        jMenuItemSemEstoque = new javax.swing.JMenuItem();
        jMenuIteDataDeSaida = new javax.swing.JMenuItem();
        jMenuItemDataDeEntrada = new javax.swing.JMenuItem();
        jMenuItemQuantidadeBaixa = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHome.setBackground(new java.awt.Color(153, 153, 255));
        jPanelHome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema De Estoque", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jMenuHome.setText("Home");
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHome);

        jMenuCadastar.setText("Cadastrar");

        jMenuItemCadastrarFornecedor.setText("Fornecedor");
        jMenuItemCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastar.add(jMenuItemCadastrarFornecedor);

        jMenuItemCadastrarProduto.setText("Produto");
        jMenuItemCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenuCadastar.add(jMenuItemCadastrarProduto);

        jMenuItemCadastrarCliente.setText("Cliente");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuCadastar.add(jMenuItemCadastrarCliente);

        jMenuBar1.add(jMenuCadastar);

        jMenu1.setText("Produto");

        jMenuItemComprar.setText("Comprar");
        jMenuItemComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemComprar);

        jMenuItemVender.setText("Vender");
        jMenuItemVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVenderActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVender);

        jMenuBar1.add(jMenu1);

        jMenuRelatorio.setText("Relatório");

        jMenuItemEstoqueAtual.setText("Estoque Atual");
        jMenuItemEstoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueAtualActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemEstoqueAtual);

        jMenuItemSemEstoque.setText("Produto Sem Estoque");
        jMenuItemSemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSemEstoqueActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemSemEstoque);

        jMenuIteDataDeSaida.setText("Data De Saida");
        jMenuIteDataDeSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteDataDeSaidaActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuIteDataDeSaida);

        jMenuItemDataDeEntrada.setText("Data De Entrada");
        jMenuItemDataDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataDeEntradaActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemDataDeEntrada);

        jMenuItemQuantidadeBaixa.setText("Quantidade Baixa");
        jMenuItemQuantidadeBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuantidadeBaixaActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemQuantidadeBaixa);

        jMenuBar1.add(jMenuRelatorio);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItem1);

        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemFornecedor);

        jMenuItem3.setText("Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItem3);

        jMenuBar1.add(jMenuPesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHomeMouseClicked
        // TODO add your handling code here:
        ocultar();
    }//GEN-LAST:event_jMenuHomeMouseClicked

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
        ocultar();        
        this.setGlassPane(cli);
        this.add(cli);
        cli.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuItemCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(fo);
        this.add(fo);
        fo.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFornecedorActionPerformed

    private void jMenuItemCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(pro);
        this.add(pro);
        pro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarProdutoActionPerformed

    private void jMenuItemComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprarActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(com);
        this.add(com);
        com.setVisible(true);
    }//GEN-LAST:event_jMenuItemComprarActionPerformed

    private void jMenuItemVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVenderActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(ven);
        this.add(ven);
        ven.setVisible(true);
    }//GEN-LAST:event_jMenuItemVenderActionPerformed

    private void jMenuItemEstoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueAtualActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(est_a);
        this.add(est_a);
        est_a.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstoqueAtualActionPerformed

    private void jMenuItemSemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSemEstoqueActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(pro_s);
        this.add(pro_s);
        pro_s.setVisible(true);
    }//GEN-LAST:event_jMenuItemSemEstoqueActionPerformed

    private void jMenuIteDataDeSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteDataDeSaidaActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(ds);
        this.add(ds);
        ds.setVisible(true);
    }//GEN-LAST:event_jMenuIteDataDeSaidaActionPerformed

    private void jMenuItemDataDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataDeEntradaActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(de);
        this.add(de);
        de.setVisible(true);
    }//GEN-LAST:event_jMenuItemDataDeEntradaActionPerformed

    private void jMenuItemQuantidadeBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuantidadeBaixaActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(qb);
        this.add(qb);
        qb.setVisible(true);
    }//GEN-LAST:event_jMenuItemQuantidadeBaixaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(pc);
        this.add(pc);
        pc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        // TODO add your handling code here:
        ocultar();        
        this.setGlassPane(pf);
        this.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         ocultar();        
        this.setGlassPane(pp);
        this.add(pp);
        pp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastar;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuIteDataDeSaida;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastrarProduto;
    private javax.swing.JMenuItem jMenuItemComprar;
    private javax.swing.JMenuItem jMenuItemDataDeEntrada;
    private javax.swing.JMenuItem jMenuItemEstoqueAtual;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemQuantidadeBaixa;
    private javax.swing.JMenuItem jMenuItemSemEstoque;
    private javax.swing.JMenuItem jMenuItemVender;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JPanel jPanelHome;
    // End of variables declaration//GEN-END:variables
}
